name: Build AutoCAD QTO

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4

    - name: Show repository files
      shell: pwsh
      run: |
        Get-ChildItem -Recurse

    - name: Find solution
      shell: pwsh
      run: |
        $sln = Get-ChildItem -Recurse -Filter *.sln

        if ($null -eq $sln) {
          Write-Host "No solution file found"
          exit 1
        }

        Write-Host "Found:"
        $sln.FullName

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore
      shell: pwsh
      run: |
        $sln = (Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1).FullName
        nuget restore "$sln"

    - name: Build
      shell: pwsh
      run: |
        $sln = (Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1).FullName
        msbuild "$sln" /p:Configuration=Release
